export default  [
  {
    "_id": "5dd0189382521b2a2fe961dc",
    "name": "The Getaway",
    "artist": "Red Hot Chili Peppers",
    "album": "The Getaway",
    "year": 2016,
    "duration": "4:10",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd036c682521b2a2fe961de",
    "name": "Dark Necessities",
    "artist": "Red Hot Chili Peppers",
    "album": "The Getaway",
    "year": 2016,
    "duration": "5:02",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c1482521b2a2fe961df",
    "name": "We Turn Red",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "3:20",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c1582521b2a2fe961e0",
    "name": "The Longest Wave",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "3:31",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c1582521b2a2fe961e1",
    "name": "Goodbye Angels",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "4:29",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c1682521b2a2fe961e2",
    "name": "Sick Love",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "3:41",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c4c82521b2a2fe961e3",
    "name": "Go Robot",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "4:24",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c4c82521b2a2fe961e4",
    "name": "Feasting on the Flowers",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "3:23",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c4c82521b2a2fe961e5",
    "name": "Detroit",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "3:47",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c4c82521b2a2fe961e6",
    "name": "This Ticonderoga",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "3:35",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c6b82521b2a2fe961e7",
    "name": "Encore",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "4:11",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c6b82521b2a2fe961e8",
    "name": "The Hunter",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "4:00",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd03c7282521b2a2fe961e9",
    "name": "Dreams of a Samurai",
    "artist": "Red Hot Chili Peppers",
    "album": "Dark Necessities",
    "year": 2016,
    "duration": "6:09",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Thegetawayalbum.jpg/220px-Thegetawayalbum.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd05d3f82521b2a2fe961ea",
    "name": "Around the World",
    "artist": "Red Hot Chili Peppers",
    "album": "Californication",
    "year": 2002,
    "duration": "3:58",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/RedHotChiliPeppersCalifornication.jpg/220px-RedHotChiliPeppersCalifornication.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd05d5382521b2a2fe961eb",
    "name": "Parallel Universe",
    "artist": "Red Hot Chili Peppers",
    "album": "Californication",
    "year": 2002,
    "duration": "4:30",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/RedHotChiliPeppersCalifornication.jpg/220px-RedHotChiliPeppersCalifornication.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd05d5582521b2a2fe961ec",
    "name": "Scar Tissue",
    "artist": "Red Hot Chili Peppers",
    "album": "Californication",
    "year": 2002,
    "duration": "3:37",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/RedHotChiliPeppersCalifornication.jpg/220px-RedHotChiliPeppersCalifornication.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd05d5882521b2a2fe961ed",
    "name": "Otherside",
    "artist": "Red Hot Chili Peppers",
    "album": "Californication",
    "year": 2002,
    "duration": "4:15",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/RedHotChiliPeppersCalifornication.jpg/220px-RedHotChiliPeppersCalifornication.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd05d5882521b2a2fe961ee",
    "name": "Get on Top",
    "artist": "Red Hot Chili Peppers",
    "album": "Californication",
    "year": 2002,
    "duration": "3:18",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/RedHotChiliPeppersCalifornication.jpg/220px-RedHotChiliPeppersCalifornication.jpg",
    "genre": "Funk Rock",
    "__v": 0
  },
  {
    "_id": "5dd073bd82521b2a2fe961ef",
    "name": "Californication",
    "artist": "Red Hot Chili Peppers",
    "album": "Californication",
    "year": 2002,
    "duration": "5:21",
    "image": "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/RedHotChiliPeppersCalifornication.jpg/220px-RedHotChiliPeppersCalifornication.jpg",
    "genre": "Funk Rock",
    "__v": 0
  }
]
